wip

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -822,19 +822,9 @@ jobs:
             function fetch_report() {
               echo "Fetching reports-$1.zip"
               wget https://output.circle-artifacts.com/output/job/${JOB_ID}/artifacts/$1/artifacts/blob-report/reports-$1.zip
-            }
-            for i in $(seq 0 7);
-            do
-              fetch_report $i
-            done
-
-            echo "Fetching reports from circle ci artifact storarge"
-            function fetch_report() {
-              echo "Fetching reports-$1.zip"
-              wget https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/$1/artifacts/blob-report/reports-$1.zip
-              if [[ $(cat reports-$1.zip) =~ "not found" ]]; then
-                echo "reports-$1.zip not found!"
-                rm reports-$1.zip
+              wgetreturn=$?
+              if [[ $wgetreturn -ne 0 ]]; then
+                echo "Failed to get reports-$1.zip"
               fi
             }
             for i in $(seq 0 7);
