fix merge steps

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -842,7 +842,37 @@ jobs:
             fi
             cd ../..
       - store_artifacts:
-          path: artifiacts/blob-report
+          path: artifacts/blob-report
+      - run:
+          name: Merge HTML reports
+          command: |
+            cd artifacts/blob-report
+            ls -l
+            JOB_ID=$(cat functional_test_job_id.txt)
+            echo "Fetching reports from circle ci artifact storarge for $JOB_ID"
+            function fetch_report() {
+              echo "Fetching reports-$1.zip"
+              wget https://output.circle-artifacts.com/output/job/${JOB_ID}/artifacts/$1/artifacts/blob-report/reports-$1.zip
+              wgetreturn=$?
+              if [[ $wgetreturn -ne 0 ]]; then
+                echo "Failed to get reports-$1.zip"
+              fi
+            }
+            for i in $(seq 0 7);
+            do
+              fetch_report $i
+            done
+
+            echo "Merging blob reports"
+            ls -l
+            if ls *.zip 1> /dev/null 2>&1; then
+            npx playwright merge-reports --reporter=html .
+            else
+              echo "No report zip files found, skipping blob merge."
+            fi
+            cd ../..
+      - store_artifacts:
+          path: playwright-report
 
   build-and-deploy-storybooks:
     executor: default-executor
